#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
loan_predict_pyspark.py

Author: Generated by Gemini Notebook
Date: August 16, 2026

Description:
    This PySpark script implements an end-to-end machine learning pipeline
    to predict loan approval outcomes (Loan_Status) using PySpark MLlib.
    It covers:
        1. SparkSession Initialization
        2. Automatic Dataset Download & Ingestion
        3. Missing Value Imputation (with detailed justification)
        4. Outlier Analysis & Treatment (with detailed justification)
        5. Numeric Variable Discretization/Binning (with detailed justification)
        6. Feature Selection (with detailed justification)
        7. Categorical Feature Label Encoding
        8. Pipeline Assembly & Vector Compilation
        9. Training and Evaluating Three Classifiers:
           - Logistic Regression
           - Decision Tree Classifier
           - Random Forest Classifier
        10. Model Comparison & Accuracy Output to 'output.txt'
"""

import os
import sys
import urllib.request
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, when, count
from pyspark.ml import Pipeline
from pyspark.ml.feature import Bucketizer, StringIndexer, VectorAssembler
from pyspark.ml.classification import LogisticRegression, DecisionTreeClassifier, RandomForestClassifier
from pyspark.ml.evaluation import MulticlassClassificationEvaluator

def main():
    # ==============================================================================
    # 1. SparkSession Initialization
    # ==============================================================================
    print("Initializing Spark Session...")
    spark = SparkSession.builder \
        .appName("Predictive Loan Modeling with PySpark") \
        .config("spark.sql.warehouse.dir", "/tmp/spark-warehouse") \
        .getOrCreate()
    
    # Adjust log level to avoid verbose logs in output
    spark.sparkContext.setLogLevel("WARN")

    # ==============================================================================
    # 2. Dataset Download & Ingestion
    # ==============================================================================
    url = "https://raw.githubusercontent.com/learningtechnologieslab/mds_cloud_computing/refs/heads/main/apache_spark/loan_data.csv"
    local_csv_path = "loan_data.csv"
    
    if not os.path.exists(local_csv_path):
        try:
            print(f"Downloading dataset from {url}...")
            urllib.request.urlretrieve(url, local_csv_path)
            print("Download complete.")
        except Exception as e:
            print(f"Error downloading dataset: {e}")
            sys.exit(1)
    else:
        print("Using existing local dataset file.")

    print(f"Loading dataset from {local_csv_path}...")
    df = spark.read.csv(local_csv_path, header=True, inferSchema=True)
    print(f"Dataset successfully loaded. Number of rows: {df.count()}, Columns: {len(df.columns)}")
    df.printSchema()

    # ==============================================================================
    # 3. Data Cleaning: Handling Missing Values
    # ==============================================================================
    # First, let's cast raw string representations of nulls (e.g., "NA", empty string)
    # to actual Spark Nulls to ensure our imputation functions catch all missing values.
    print("\n[Step 1] Preprocessing: Cleaning and replacing text nulls...")
    for column in df.columns:
        df = df.withColumn(column, when(col(column).isin("", "NA", "null", "NULL"), None).otherwise(col(column)))

    # Let's count missing values per column before we proceed
    print("Missing value counts before imputation:")
    df.select([count(when(col(c).isNull(), c)).alias(c) for c in df.columns]).show()

    # ==============================================================================
    # JUSTIFICATION FOR HANDLING MISSING VALUES:
    # 1. Categorical Columns (Gender, Married, Dependents, Self_Employed):
    #    We impute missing values using the MODE (most frequent value) of each respective
    #    column. This is a standard and robust approach for categorical data since it
    #    preserves the overall distribution and frequency structure without introducing
    #    non-existent categories.
    # 2. Credit_History:
    #    We treat Credit_History as a categorical variable and impute missing values
    #    with its mode (typically 1.0, representing good credit). Good credit is the
    #    dominant status, and this represents a conservative baseline.
    # 3. Numerical Columns (LoanAmount, Loan_Amount_Term):
    #    We impute missing values using the MEDIAN. The median is far more robust to
    #    outliers and skewed distributions (which is typical for financial metrics like
    #    loan amounts) compared to the mean, preventing distorted imputations.
    # ==============================================================================

    # Helper function to compute mode programmatically
    def get_mode(dataframe, col_name):
        mode_row = dataframe.filter(col(col_name).isNotNull() & (col(col_name) != "")) \
                            .groupBy(col_name).count().orderBy("count", ascending=False)
        if mode_row.count() > 0:
            return mode_row.first()[0]
        return None

    # Helper function to compute median programmatically
    def get_median(dataframe, col_name):
        non_null_df = dataframe.filter(col(col_name).isNotNull())
        if non_null_df.count() > 0:
            return non_null_df.approxQuantile(col_name, [0.5], 0.001)[0]
        return None

    # Apply imputation
    print("Imputing missing values...")
    
    # Categorical Columns Imputation
    categorical_to_impute = ["Gender", "Married", "Dependents", "Self_Employed", "Credit_History"]
    for cat_col in categorical_to_impute:
        col_mode = get_mode(df, cat_col)
        if col_mode is not None:
            # Credit_History might be numeric or string; handle casting appropriately
            if cat_col == "Credit_History":
                df = df.withColumn(cat_col, col(cat_col).cast("double"))
                col_mode = float(col_mode)
            print(f"  - Imputing categorical '{cat_col}' missing values with mode: '{col_mode}'")
            df = df.fillna({cat_col: col_mode})

    # Numerical Columns Imputation
    # Note: ApplicantIncome and CoapplicantIncome typically do not have missing values,
    # but we include them in our robust check just in case.
    numerical_to_impute = ["ApplicantIncome", "CoapplicantIncome", "LoanAmount", "Loan_Amount_Term"]
    for num_col in numerical_to_impute:
        # Cast to double to ensure consistent type
        df = df.withColumn(num_col, col(num_col).cast("double"))
        col_median = get_median(df, num_col)
        if col_median is not None:
            print(f"  - Imputing numerical '{num_col}' missing values with median: {col_median}")
            df = df.fillna({num_col: col_median})

    # Verify that there are no missing values remaining
    print("\nMissing value counts after imputation:")
    df.select([count(when(col(c).isNull(), c)).alias(c) for c in df.columns]).show()

    # ==============================================================================
    # 4. Outlier Detection & Treatment
    # ==============================================================================
    # ==============================================================================
    # JUSTIFICATION FOR OUTLIER DETECTION AND TREATMENT:
    # 1. Outlier Detection: Outliers in variables like ApplicantIncome and LoanAmount
    #    can be identified using standard statistical methods (e.g., IQR - Interquartile Range).
    # 2. Decision - KEEP Outliers: We decide to KEEP the outliers in our dataset instead
    #    of dropping them.
    #    Reasoning:
    #    - Business Context: High-income applicants and exceptionally large loan requests are
    #      real, valid cases in loan applications. Dropping them would lead to a model that
    #      cannot generalize to high-net-worth clients or premium loans.
    #    - Mitigation via Discretization: Since we are discretizing (binning) these continuous
    #      variables later in the pipeline, extreme outlier values will naturally fall into
    #      the highest bin (e.g., "Very High"). This grouping naturally controls the high leverage/
    #      influence of these extreme values on model parameters without losing valid data.
    # ==============================================================================
    print("\n[Step 2] Outlier Analysis:")
    for col_name in ["ApplicantIncome", "LoanAmount"]:
        # Let's programmatically print outlier boundaries for information
        q1, q3 = df.approxQuantile(col_name, [0.25, 0.75], 0.001)
        iqr = q3 - q1
        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr
        outlier_count = df.filter((col(col_name) < lower_bound) | (col(col_name) > upper_bound)).count()
        print(f"  - For {col_name}: Q1={q1}, Q3={q3}, IQR={iqr}")
        print(f"    Outlier Boundaries: Lower={lower_bound}, Upper={upper_bound}")
        print(f"    Detected Outliers count: {outlier_count} (Decision: KEPT because discretization handles them natively)")

    # ==============================================================================
    # 5. Feature Discretization
    # ==============================================================================
    # ==============================================================================
    # JUSTIFICATION FOR DISCRETIZATION (BINNING) OF NUMERIC COLUMNS:
    # 1. ApplicantIncome:
    #    - Bins: [0.0, 3000.0, 6000.0, 10000.0, float('inf')]
    #    - Reasoning: Splits represent realistic socio-economic income tiers: Low Income (<3k),
    #      Lower-Middle (3k-6k), Upper-Middle (6k-10k), and High Income (>10k).
    # 2. CoapplicantIncome:
    #    - Bins: [-1.0, 1.0, 3000.0, float('inf')]
    #    - Reasoning: Isolates cases with no co-applicant (0.0 income is binned as [-1.0 to 1.0]),
    #      moderate secondary income (1k to 3k), and high secondary income (>3k).
    # 3. LoanAmount:
    #    - Bins: [0.0, 100.0, 200.0, 350.0, float('inf')]
    #    - Reasoning: Captures levels of debt requests: Small (<100k), Standard (100k-200k),
    #      Large (200k-350k), and Premium (>350k).
    # 4. Loan_Amount_Term:
    #    - Bins: [0.0, 180.0, 300.0, 360.0, float('inf')]
    #    - Reasoning: Categorizes duration into Short-Term (<15 years), Medium-Term (15-25 years),
    #      Standard 30-Year term (360 months), and Long-Term (>30 years).
    #
    # Discretization helps classifiers (especially linear ones like Logistic Regression)
    # model non-linear relationships and reduces the impact of scale differences.
    # ==============================================================================
    print("\n[Step 3] Discretizing numeric columns into structured categories...")
    
    applicant_income_bucket = Bucketizer(
        splits=[0.0, 3000.0, 6000.0, 10000.0, float('inf')],
        inputCol="ApplicantIncome",
        outputCol="ApplicantIncome_Bin"
    )

    coapplicant_income_bucket = Bucketizer(
        splits=[-1.0, 1.0, 3000.0, float('inf')],
        inputCol="CoapplicantIncome",
        outputCol="CoapplicantIncome_Bin"
    )

    loan_amount_bucket = Bucketizer(
        splits=[0.0, 100.0, 200.0, 350.0, float('inf')],
        inputCol="LoanAmount",
        outputCol="LoanAmount_Bin"
    )

    # Standardize Loan_Amount_Term values as Double to avoid bucketizer schema errors
    df = df.withColumn("Loan_Amount_Term", col("Loan_Amount_Term").cast("double"))
    loan_term_bucket = Bucketizer(
        splits=[0.0, 180.0, 300.0, 360.0, float('inf')],
        inputCol="Loan_Amount_Term",
        outputCol="Loan_Amount_Term_Bin"
    )

    # ==============================================================================
    # 6. Feature Selection
    # ==============================================================================
    # ==============================================================================
    # JUSTIFICATION FOR FEATURE SELECTION:
    # - Included Predictors:
    #   1. Gender_Index, Married_Index, Dependents_Index, Education_Index, Self_Employed_Index,
    #      Property_Area_Index: Classic socio-demographic features that reflect stability.
    #   2. Credit_History: Historically the single strongest indicator of loan repayment success.
    #   3. ApplicantIncome_Bin, CoapplicantIncome_Bin, LoanAmount_Bin, Loan_Amount_Term_Bin:
    #      Our robust discretized financial predictors.
    # - Excluded Predictors:
    #   1. Loan_ID: A unique applicant primary key. It contains no generalizable patterns
    #      and would cause overfitting/noise.
    #   2. Raw Numerical Features (ApplicantIncome, CoapplicantIncome, LoanAmount, Loan_Amount_Term):
    #      Including both the raw and discretized columns would cause severe multi-collinearity
    #      and redundancy, destabilizing models like Logistic Regression.
    # ==============================================================================
    print("\n[Step 4] Configuring Categorical Label Encoding and Vector Assembler...")
    
    # Columns to label encode (we handle missing values before doing this)
    categorical_cols = ["Gender", "Married", "Dependents", "Education", "Self_Employed", "Property_Area"]
    
    indexers = [
        StringIndexer(inputCol=col_name, outputCol=col_name + "_Index", handleInvalid="keep")
        for col_name in categorical_cols
    ]

    # Label encoding for the Target Variable 'Loan_Status' (Y -> 1.0, N -> 0.0)
    target_indexer = StringIndexer(inputCol="Loan_Status", outputCol="label", handleInvalid="keep")

    # List of engineered features to construct our feature vector
    feature_cols = [
        "Gender_Index", "Married_Index", "Dependents_Index", "Education_Index", 
        "Self_Employed_Index", "Property_Area_Index", "Credit_History",
        "ApplicantIncome_Bin", "CoapplicantIncome_Bin", "LoanAmount_Bin", "Loan_Amount_Term_Bin"
    ]

    assembler = VectorAssembler(inputCols=feature_cols, outputCol="features")

    # ==============================================================================
    # 7. Pipeline Construction & Data Preprocessing Execution
    # ==============================================================================
    print("Assembling and running the preprocessing Pipeline...")
    preprocessing_pipeline = Pipeline(stages=[
        applicant_income_bucket,
        coapplicant_income_bucket,
        loan_amount_bucket,
        loan_term_bucket,
        *indexers,
        target_indexer,
        assembler
    ])

    pipeline_model = preprocessing_pipeline.fit(df)
    processed_df = pipeline_model.transform(df)

    # Let's print out the final dataset structure
    print("\nProcessed Data Schema:")
    processed_df.select("features", "label").show(5, truncate=False)

    # ==============================================================================
    # 8. Model Training, Evaluation & Comparison
    # ==============================================================================
    # Split preprocessed data into train and test sets (80% train, 20% test)
    # Seed 42 ensures reproducible train/test partition.
    print("\n[Step 5] Partitioning data into Train (80%) and Test (20%) sets...")
    train_data, test_data = processed_df.randomSplit([0.8, 0.2], seed=42)
    print(f"  - Training records count: {train_data.count()}")
    print(f"  - Testing records count: {test_data.count()}")

    # ==============================================================================
    # JUSTIFICATION FOR SELECTION OF CLASSIFIERS:
    # We select three diverse and robust machine learning algorithms from MLlib:
    # 1. Logistic Regression:
    #    - A widely used, interpretable baseline model for binary classification.
    #    - Excellent for understanding feature weights and relationship directions.
    # 2. Decision Tree Classifier:
    #    - A non-parametric model that naturally handles interactions and non-linear boundaries.
    #    - Highly interpretable and matches the decision-making logic of credit underwriters.
    # 3. Random Forest Classifier:
    #    - An ensemble method of bagging multiple decision trees.
    #    - Significantly reduces overfitting, handles high variance, and typically yields
    #      superior predictive accuracy compared to a single decision tree.
    # ==============================================================================
    
    print("\nTraining models and evaluating accuracies...")
    
    # Initialize Multi-class classification evaluator for accuracy
    evaluator = MulticlassClassificationEvaluator(labelCol="label", predictionCol="prediction", metricName="accuracy")

    # 1. Logistic Regression Classifier
    print("Training Classifier 1: Logistic Regression...")
    lr = LogisticRegression(featuresCol="features", labelCol="label", maxIter=10)
    lr_model = lr.fit(train_data)
    lr_preds = lr_model.transform(test_data)
    lr_accuracy = evaluator.evaluate(lr_preds)
    print(f"  -> Logistic Regression Accuracy: {lr_accuracy:.4%}")

    # 2. Decision Tree Classifier
    print("Training Classifier 2: Decision Tree...")
    dt = DecisionTreeClassifier(featuresCol="features", labelCol="label", seed=42)
    dt_model = dt.fit(train_data)
    dt_preds = dt_model.transform(test_data)
    dt_accuracy = evaluator.evaluate(dt_preds)
    print(f"  -> Decision Tree Accuracy: {dt_accuracy:.4%}")

    # 3. Random Forest Classifier
    print("Training Classifier 3: Random Forest...")
    rf = RandomForestClassifier(featuresCol="features", labelCol="label", numTrees=50, seed=42)
    rf_model = rf.fit(train_data)
    rf_preds = rf_model.transform(test_data)
    rf_accuracy = evaluator.evaluate(rf_preds)
    print(f"  -> Random Forest Accuracy: {rf_accuracy:.4%}")

    # ==============================================================================
    # 9. Output to Text File (output.txt)
    # ==============================================================================
    output_filename = "output.txt"
    print(f"\n[Step 6] Saving final evaluation results to '{output_filename}'...")
    
    output_content = (
        "========================================================\n"
        "PySpark MLlib Model Evaluation Results - Loan Approval\n"
        "========================================================\n"
        f"1. Logistic Regression Accuracy : {lr_accuracy:.4%}\n"
        f"2. Decision Tree Accuracy       : {dt_accuracy:.4%}\n"
        f"3. Random Forest Accuracy        : {rf_accuracy:.4%}\n"
        "========================================================\n"
        "Brief Analysis & Insights:\n"
        "- Logistic Regression provides a robust, linear-boundary baseline.\n"
        "- Decision Tree represents a highly interpretable single tree with rule-based structures.\n"
        "- Random Forest acts as an ensemble model, reducing variance and typically offering the best generalization.\n"
        "Note: Results may vary slightly depending on partition splits and system resources.\n"
    )
    
    try:
        with open(output_filename, "w", encoding="utf-8") as f:
            f.write(output_content)
        print(f"Successfully wrote accuracy report to: '{os.path.abspath(output_filename)}'")
    except Exception as e:
        print(f"Error writing output file: {e}")

    # Clean up and stop Spark session
    print("\nStopping Spark Session...")
    spark.stop()
    print("Execution complete. All steps of the PySpark ML pipeline executed successfully.")

if __name__ == "__main__":
    main()
